from odoo import models, fields


class DocumentRequirements(models.Model):
    _name = 'document.requirements'
    _description = 'Document Requirements'

    passport_alteration = fields.Many2many('ir.attachment', 'passport_alteration_rel', string='Alteration page in the passport if available / Change of name deed')
    passport_scan = fields.Many2many('ir.attachment', 'passport_scan_rel', string='Scanned copy of the first 2 pages of the passport')
    driving_license_scan = fields.Many2many('ir.attachment', 'driving_license_scan_rel', string='Scanned copy of the two sides of Driving License')
    brp_scan = fields.Many2many('ir.attachment', 'brp_scan_rel', string='Scanned copy of both sides of your BRP / Visa Stamp')
    sharecode_hmrc = fields.Many2many('ir.attachment', 'sharecode_hmrc_rel', string='Sharecode for Immigration Status downloaded by HMRC')
    utility_bill = fields.Many2many('ir.attachment', 'utility_bill_rel', string='Electricity/Gas/Landline Bill')
    council_tax_bill = fields.Many2many('ir.attachment', 'council_tax_bill_rel', string='Latest Council Tax Bill')
    appointment_letter = fields.Many2many('ir.attachment', 'appointment_letter_rel', string='Employment Appointment Letter')
    current_contract = fields.Many2many('ir.attachment', 'current_contract_rel', string='Current Contract')
    bonus_payslips = fields.Many2many('ir.attachment', 'bonus_payslips_rel', string='Last 2 years Bonus Payslips')
    latest_payslips = fields.Many2many('ir.attachment', 'latest_payslips_rel', string='Latest 3 months Payslips')
    p60 = fields.Many2many('ir.attachment', 'p60_rel', string='Last 2 years P60')
    bank_statements_salary = fields.Many2many('ir.attachment', 'bank_statements_salary_rel', string='Latest 3 months Bank Statements - Salary')
    salary_increment_letter = fields.Many2many('ir.attachment', 'salary_increment_letter_rel', string='Salary Increment Letter')
    bank_statements_pension = fields.Many2many('ir.attachment', 'bank_statements_pension_rel', string='Latest 3 months Bank Statements - Pension')
    pension_forecast = fields.Many2many('ir.attachment', 'pension_forecast_rel', string='Pension Forecast')
    tax_documents = fields.Many2many('ir.attachment', 'tax_documents_rel', string='Last 2 years Tax Documents')
    company_bank_statements = fields.Many2many('ir.attachment', 'company_bank_statements_rel', string='Latest 3 months Company Bank Statements')
    company_accounts = fields.Many2many('ir.attachment', 'company_accounts_rel', string='Signed and Finalized Latest 2 years Company Accounts')
    other_income_bank_statements = fields.Many2many('ir.attachment', 'other_income_bank_statements_rel', string='Latest 3 months Bank Statements - Other Income')
    tax_credit_statement = fields.Many2many('ir.attachment', 'tax_credit_statement_rel', string='Statement from HMRC for Tax Credits')
    universal_credit_statements = fields.Many2many('ir.attachment', 'universal_credit_statements_rel', string='Latest 3 months Statements of Universal Tax Credit')
    child_tax_credit_award = fields.Many2many('ir.attachment', 'child_tax_credit_award_rel', string='Child Tax Credit Award Letter')
    pip_dla_letter = fields.Many2many('ir.attachment', 'pip_dla_letter_rel', string='PIP/DLA Letter')
    credit_report = fields.Many2many('ir.attachment', 'credit_report_rel', string='Latest Multi Agency Credit Report')
    clearance_statement = fields.Many2many('ir.attachment', 'clearance_statement_rel', string='Latest Clearance Statement')
    bank_statements_expenses = fields.Many2many('ir.attachment', 'bank_statements_expenses_rel', string='Latest 3 months Bank Statements - Monthly Expenses')
    direct_debit_account_statement = fields.Many2many('ir.attachment', 'direct_debit_account_statement_rel', string='Latest Bank Statement of Direct Debit Account')
    reservation_form = fields.Many2many('ir.attachment', 'reservation_form_rel', string='Reservation Form')
    cml_form = fields.Many2many('ir.attachment', 'cml_form_rel', string='CML Form')
    memorandum_of_sale = fields.Many2many('ir.attachment', 'memorandum_of_sale_rel', string='Memorandum of Sale')
    epc = fields.Many2many('ir.attachment', 'epc_rel', string='EPC')
    pea = fields.Many2many('ir.attachment', 'pea_rel', string='PEA')
    bank_statements_deposit = fields.Many2many('ir.attachment', 'bank_statements_deposit_rel', string='Latest 3 months Bank Statements - Deposit Source')
    gifted_deposit_format = fields.Many2many('ir.attachment', 'gifted_deposit_format_rel', string='Format of Gifted Deposit')
    donor_bank_statements = fields.Many2many('ir.attachment', 'donor_bank_statements_rel', string='Latest 3 months Bank Statements of Donor')
    tenancy_agreement_btl = fields.Many2many('ir.attachment', 'tenancy_agreement_btl_rel', string='Tenancy Agreement for BTL Remortgage')
    bank_statements_rental_income = fields.Many2many('ir.attachment', 'bank_statements_rental_income_rel', string='Latest 3 months Bank Statements - Rental Income')
    bank_statements_btl_mortgage = fields.Many2many('ir.attachment', 'bank_statements_btl_mortgage_rel', string='Latest 3 months Bank Statements - BTL Mortgage Payments')
    mortgage_statement = fields.Many2many('ir.attachment', 'mortgage_statement_rel', string='Mortgage Statement')
    htb_annual_payment_letter = fields.Many2many('ir.attachment', 'htb_annual_payment_letter_rel', string='Latest Annual Payment Information Letter for HTB Loan')
    arla_letter = fields.Many2many('ir.attachment', 'arla_letter_rel', string='ARLA Letter')
    sales_particulars = fields.Many2many('ir.attachment', 'sales_particulars_rel', string='Sales Particulars')
    multiple_occupants_tenancy_agreements = fields.Many2many('ir.attachment', 'multiple_occupants_tenancy_agreements_rel', string='Tenancy Agreements for Multiple Occupants')
    spv_bank_statements = fields.Many2many('ir.attachment', 'spv_bank_statements_rel', string='Latest 3 months Bank Statements of the SPV')
    solicitor_quotation_ids = fields.Many2many('ir.attachment', 'solicitor_attachment_rel', string='Solicitor Quotation')
