{
    'name': 'BVS CRM',
    'version': '1.0',
    'category': '',
    'sequence': 1,
    'author': 'Nerosoft Solutions',
    'website': 'https://nerosoftsolutions.com/',
    'summary': 'Manage Leads',
    'description': """Manage Leads""",
    'depends': ['base', 'mail', 'web','portal'],
    'data': [
        'data/ir_sequence_data.xml',
        'data/emai_templates.xml',
        'data/sla_date_notification_email_template.xml',
        'data/mortgage_advisor_reminder_email_template.xml',
        'data/completion_date_notification_email_template.xml',
        'data/ready_to_submit_email_template.xml',
        'security/ir.model.access.csv',
        'security/lead_security.xml',
        'wizard/add_applicant_wizard.xml',
        'wizard/fact_find_partner_wizard.xml',
        'wizard/delete_applicant_wizard_view.xml',
        'views/res_users.xml',
        'views/res_partner.xml',
        'views/bvs_stage.xml',
        'views/bvs_estate_agent.xml',
        'views/bvs_applicant_form_view.xml',
        'views/bvs_lead_view.xml',
        'views/mortgage.xml',
        'views/mortgage_affordability.xml',
        'views/mortgage_dip.xml',
        'views/mortgage_illustration.xml',
        'views/mortgage_pre_offer.xml',
        'views/mortgage_post_offer.xml',
        'views/mortgage_completion.xml',
        'views/mortgage_esis_record_details.xml',
        'views/event_list.xml',
        'views/bvs_solicitor_view.xml',
        'views/protection.xml',
        'views/protection_application.xml',
        'views/protection_completion.xml',
        'views/protection_quote_record_details.xml',
        'data/valuation_mail_template.xml',
        'menus/bvs_menu.xml',
    ],

    'assets': {
        'web.assets_frontend': [
            'bvs_crm/static/src/js/bvs_crm.js',
        ],
    },

    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
