{
    'name': 'BVS Fact Find',
    'version': '1.0',
    'category': '',
    'sequence': 1,
    'author': 'Nerosoft Solutions',
    'website': 'https://nerosoftsolutions.com/',
    'summary': 'Fact Find',
    'description': """Create Fact Find & Manage KYC""",
    'depends': ['base', 'bvs_crm', 'bvs_portal', 'bvs_notification'],
    'data': [
        'security/ir.model.access.csv',
        'templates/client_portal_templates.xml',
        'templates/fact_find_form_portal.xml',
        'views/bvs_lead.xml',
        'views/fact_find_view.xml',
        'views/address_history.xml',
        'views/financial_dependants.xml',
        'views/employement_details.xml',
        'views/self_employed.xml',
        'views/other_income.xml',
        'views/adverse_credit.xml',
        'views/credit_comment.xml',
        'views/monthly_expenses.xml',
        'views/bank_details.xml',
        'views/deposit.xml',
        'views/new_property_details.xml',
        'views/estate_agent.xml',
        'views/solicitor.xml',
        'views/existing_properties.xml',
        'views/existing_mortgage.xml',
        'views/protection.xml',
        'views/property_portfolio.xml',
        'views/fact_find_document.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            # 'bvs_fact_find/static/src/js/fact_find.js',
            'bvs_fact_find/static/src/js/fact_find_multiple.js',
            'bvs_fact_find/static/src/js/fact_find_employment_details.js',
            'bvs_fact_find/static/src/js/fact_find_credit_comment.js',
            'bvs_fact_find/static/src/js/fact_find_adverse_credit.js',
            'bvs_fact_find/static/src/js/fact_find_existing_mortgage.js',
            'bvs_fact_find/static/src/js/fact_find_existing_properties.js',
            'bvs_fact_find/static/src/js/fact_find_protection.js',
            'bvs_fact_find/static/src/js/fact_find_self_employment_details.js',
            'bvs_fact_find/static/src/js/fact_find_deposit.js',
            'bvs_fact_find/static/src/js/fact_find_address_history.js',
            'bvs_fact_find/static/src/js/fact_find_bank_details.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
